master:
  build: master
  volumes:
      - C:\work\db\redis_master\data:/data
      - C:\work\db\redis_master\log:/var/redis/log/
  ports:
      - 6379:6379
slave:
  build: slave
  volumes:
      - C:\work\db\redis_slave\data:/data
      - C:\work\db\redis_slave\log:/var/redis/log/
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000  
  volumes:
    - C:\work\db\sentinel\log:/var/redis/log/
  links:
    - master:redis-master
    - slave
  ports:
    - 26379:26379
phpRedisAdmin:
  image: erikdubbelboer/phpredisadmin
  environment:
     - REDIS_1_HOST=redis-master
     - REDIS_1_NAME=mymaster
  ports:
     - 8081:80
  links:
     - master:redis-master
     - sentinel