master:
  image: redis:3.2.11
  volumes:
      - C:\work\db\redis_master:/data
  ports:
      - 6379:6379
slave:
  image: redis:3.2.11
  command: redis-server --slaveof redis-master 6379
  volumes:
      - C:\work\db\redis_slave:/data
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave
  ports:
    - 26379:26379
phpRedisAdmin:
  image: erikdubbelboer/phpredisadmin
  environment:
     - REDIS_1_HOST=redis-master
     - REDIS_1_NAME=mymaster
  ports:
     - 8081:80
  links:
     - master:redis-master
     - sentinel